version: '3.8'
services:
  bank:
    build:
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=bank
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/bank
    networks:
      - postgres
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bank
    ports:
      - '5432:5432'
    networks:
      postgres:
        ipv4_address: 172.10.1.1
    volumes:
      - db:/var/lib/postgresql
      - ./init-database.sh:/docker-entrypoint-initdb.d/db_init.sh
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - db
networks:
  postgres:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.10.0.0/16
volumes:
  db:
    driver: local
  pgadmin:
    driver: local